---
title: "Get Owner, Sales, & Building Info"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(RSelenium)
library(lubridate)
library(readxl)
library(rlist)
library(plyr)
library(hablar)
```
```{r}
# this chunk initiates a new selenium server, if you get an error, it's usually because the port is already in use, change the first argument of rs(Driver) to four random digits followed by an L
rD <- rsDriver(2673L, "firefox")
rmDR <- rD[["client"]]
```

```{r}
get_assessor_info <- possibly(function(address){
  # get the current time and pause after running for 45 minutes
  currenttime <- now()
  if(currenttime > endtime){
    # if time is up, flag this record for removal (it gets filtered out in below chunk)
    return("Drop this")
    break 
  } else {
    # if time isn't up, proceed to grab the table
    print(paste0("It is now ",
                 currenttime,
                 ", I will stop at ",
                 endtime))
    # take small breaks so we don't cause problems for their server
    Sys.sleep(runif(1,5,25))
    # navigate to the first page
    rmDR$navigate("http://gis.vgsi.com/nantucketma/Search.aspx")
    Sys.sleep(runif(1,1,5))
    
    # identify the search bar (try using the selector gadget chrome extension if unsure)
    search_bar <- rmDR$findElement("css selector", "#MainContent_txtSearchAddress")
    Sys.sleep(runif(1,1,5))
    
    # submit a query for the address
    search_bar$sendKeysToElement(list(address, key = "enter"))
    
    # take a quick breather while the content is sent over
    Sys.sleep(runif(1,1,5))
    
    # now look for it  
    address_link <- rmDR$findElement("link text", address)
    Sys.sleep(runif(1,1,3))
    
    # click the hyperlink taking you to the page for that specific property
    address_link$clickElement()
    Sys.sleep(runif(1,1,3))
    
    # copy down this url
    url <- rmDR$getCurrentUrl()
    Sys.sleep(runif(1,1,3))
    
################################################################################    
    # using rvest to pull in the info from the page
    
    url_pull <- url[[1]] %>%
    
    # read in the html  
    read_html()
    
    # initialize results list
    result_list <- list()
    
    categories <- c("Owner Name",
                    "Owner Address", 
                    "Attributes",
                    "Sales History")
    
    selectors <- c("#MainContent_lblOwner",
                   "#MainContent_lblAddr1",
                   "table#MainContent_ctl01_grdCns.GridViewStyle",
                   "table#MainContent_grdSales.GridViewStyle")
    
    # pull in the text attributes
    for(i in 1:2){
      result_list[[i]] <- url_pull %>% 
        html_nodes(css = selectors[i]) %>% 
        html_text()
    }
    # pull in the tables
    for(i in 3:4){
      table <- url_pull %>% 
        html_nodes(css = selectors[i]) %>% 
        html_table() %>% 
        tibble()
      if(i == 3){ # if pulling in attributes, convert to wide format and add address so we can merge
        table <- table[[1]][[1]] %>% 
          tibble() %>% 
          pivot_wider(names_from = colnames(table[[1]][[1]][1]),
                      values_from = colnames(table[[1]][[1]][2]))%>%
          mutate(Address = address)
      } else { # if pulling in sales history, just add the address
        table <- table[[1]][[1]] %>% 
          tibble() %>% 
          mutate(Address = address)
      }
      result_list[[i]] <- table
      }
    names(result_list) <- categories
    print(paste0("I successfully pulled ",
                 address,
                 "!"))
    return(result_list)
  }
},
    otherwise = "Address not Found")

```

```{r}
endtime <- now()+3*60*60
addresses <- c("1 A ST", "43 MILLBROOK RD", "9 OCEAN AV")
allinfo <- map(addresses,get_assessor_info)

names(allinfo) <- addresses[1:length(allinfo)]
allinfo <- allinfo[allinfo != "Drop this"]
save(allinfo, file = "allinfo.RData")
```



```{r}
# make the data frames
# make a df of the owner information for all properties
owner_list <- list()
for(i in 1:length(allinfo)){
  owner_list[[i]] <- list()
  owner_list[[i]][1] <- allinfo[[names(allinfo)[i]]][1]
  owner_list[[i]][2] <- allinfo[[names(allinfo)[i]]][2]
  owner_list[[i]] <- Reduce("rbind", owner_list[[i]]) %>%
    tibble() %>% 
    mutate(v = c("Owner Name", "Owner Address"))
  colnames(owner_list[[i]]) <- c("Value", "Variable")
  owner_list[[i]] <- owner_list[[i]] %>% 
  pivot_wider(names_from = Variable, values_from = Value) %>% 
  mutate(`Property Address` = names(allinfo)[i])
}
Owners_df <- Reduce("rbind.fill", owner_list)

attribute_list <- list()
for(i in 1:length(allinfo)){
  attribute_list[i] <- allinfo[[names(allinfo)[i]]][3]
}

Attribute_df <- Reduce("rbind.fill", attribute_list)


sales_list <- list()
for(i in 1:length(allinfo_p3)){
  sales_list[i] <- allinfo_p3[[names(allinfo)[i]]][4]
}

Sales_df <- Reduce("rbind.fill", sales_list)
```

```{r}
# write files to csvs
Attribute_df <- Attribute_df %>% 
  tibble() %>% 
  convert(chr(names(Attribute_df)))
 
write_csv(Attribute_df,"Attributes_p1_3_30.csv")
write_csv(Owners_df,"Owner_p1_3_30.csv")
write_csv(Sales_df,"Sales_p1_3_30.csv")
```
